package com.example.databasecopier.adapter

import java.sql.Connection
import java.sql.DriverManager

class JdbcTargetAdapter(private val config: ConnectionConfig) : TargetAdapter {

    private lateinit var connection: Connection

    override fun connect() {
        connection = DriverManager.getConnection(buildJdbcUrl(config), config.username, config.password)
        connection.autoCommit = false
    }

    override fun createTable(structure: TableStructure) {
        // В SQLite автоинкремент возможен только через "INTEGER PRIMARY KEY AUTOINCREMENT" прямо
        // в определении колонки (rowid alias) — там нельзя одновременно иметь отдельный табличный
        // PRIMARY KEY(...) для этой же колонки, поэтому это единственный особый случай ниже.
        val sqliteAutoIncPk = if (config.type == DbType.SQLITE) {
            structure.primaryKey.singleOrNull()?.let { pk -> structure.columns.firstOrNull { it.name == pk && it.autoIncrement } }
        } else null

        val columnsSql = structure.columns.joinToString(", ") { col ->
            buildColumnSql(col, isSqliteAutoIncPk = col.name == sqliteAutoIncPk?.name)
        }
        val pkSql = if (structure.primaryKey.isNotEmpty() && sqliteAutoIncPk == null) {
            ", PRIMARY KEY (${structure.primaryKey.joinToString(", ") { quote(it) }})"
        } else ""

        // MySQL позволяет задать комментарий таблицы прямо в CREATE TABLE — остальным СУБД
        // (кроме SQLite, где комментарии не поддерживаются) это делается отдельным statement'ом
        // после создания таблицы, см. applyTableAndColumnComments().
        val tableCommentSql = if (config.type == DbType.MYSQL) {
            structure.comment?.let { " COMMENT=${stringLiteral(it)}" } ?: ""
        } else ""

        connection.createStatement().use { stmt ->
            // Если таблица с таким именем уже существует на target — она безусловно удаляется
            // и создаётся заново по структуре источника (решение зафиксировано с пользователем:
            // не пытаться угадывать совместимость существующей схемы, а гарантировать, что
            // структура target всегда точно соответствует source).
            stmt.execute("DROP TABLE IF EXISTS ${quote(structure.name)}")
            stmt.execute("CREATE TABLE ${quote(structure.name)} ($columnsSql$pkSql)$tableCommentSql")
        }
        connection.commit()

        if (config.type == DbType.POSTGRESQL || config.type == DbType.SQLSERVER) {
            applyTableAndColumnComments(structure)
        }
    }

    private fun applyTableAndColumnComments(structure: TableStructure) {
        connection.createStatement().use { stmt ->
            structure.comment?.let { comment ->
                val sql = when (config.type) {
                    DbType.POSTGRESQL -> "COMMENT ON TABLE ${quote(structure.name)} IS ${stringLiteral(comment)}"
                    DbType.SQLSERVER -> "EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N${stringLiteral(comment)}, " +
                        "@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'${structure.name.replace("'", "''")}'"
                    else -> return@let
                }
                stmt.execute(sql)
            }
            for (col in structure.columns) {
                val comment = col.comment ?: continue
                val sql = when (config.type) {
                    DbType.POSTGRESQL ->
                        "COMMENT ON COLUMN ${quote(structure.name)}.${quote(col.name)} IS ${stringLiteral(comment)}"
                    DbType.SQLSERVER ->
                        "EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N${stringLiteral(comment)}, " +
                            "@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'${structure.name.replace("'", "''")}', " +
                            "@level2type=N'COLUMN', @level2name=N'${col.name.replace("'", "''")}'"
                    else -> continue
                }
                stmt.execute(sql)
            }
        }
        connection.commit()
    }

    private fun stringLiteral(value: String): String = "'${value.replace("'", "''")}'"

    private fun buildColumnSql(col: ColumnDef, isSqliteAutoIncPk: Boolean): String {
        if (isSqliteAutoIncPk) return "${quote(col.name)} INTEGER PRIMARY KEY AUTOINCREMENT"

        val sqlType = TypeMapper.toSqlType(config.type, col.type)
        // Автоинкремент всегда генерируется нативным механизмом целевой СУБД, а не переносом
        // сырого выражения источника (nextval('seq') в MySQL не имеет смысла и наоборот).
        val autoIncrementSql = if (col.autoIncrement) when (config.type) {
            DbType.MYSQL -> " AUTO_INCREMENT"
            // BY DEFAULT (а не ALWAYS) — копирование вставляет оригинальные PK-значения источника
            // явно, а ALWAYS запрещает это без отдельного OVERRIDING SYSTEM VALUE на каждый INSERT.
            DbType.POSTGRESQL -> " GENERATED BY DEFAULT AS IDENTITY"
            DbType.SQLSERVER -> " IDENTITY(1,1)"
            // Композитный PK с автоинкрементом в SQLite не имеет смысла — тут ничего не добавляем,
            // единственный поддерживаемый случай (одиночный PK) обработан через isSqliteAutoIncPk.
            DbType.SQLITE -> ""
        } else ""
        val nullability = if (col.nullable) "" else " NOT NULL"
        val defaultSql = safeDefaultSql(col.defaultValue)?.let { " DEFAULT $it" } ?: ""
        val collationSql = safeCollationSql(col.collation)
        // MySQL — единственная СУБД здесь, где комментарий колонки можно (и нужно) задать прямо
        // в CREATE TABLE; для Postgres/MSSQL это отдельный statement после создания таблицы,
        // см. applyTableAndColumnComments().
        val commentSql = if (config.type == DbType.MYSQL) col.comment?.let { " COMMENT ${stringLiteral(it)}" } ?: "" else ""
        return "${quote(col.name)} $sqlType$collationSql$autoIncrementSql$nullability$defaultSql$commentSql"
    }

    // Имя collation одного диалекта почти никогда не валидно в другом (например Postgres
    // "en_US.utf8" против MySQL "utf8mb4_unicode_ci"), поэтому переносим только для MySQL/MSSQL,
    // где формат имени — простой идентификатор, и только если он проходит базовую санацию.
    // Postgres/SQLite как target — молча пропускаем.
    private fun safeCollationSql(raw: String?): String {
        if (raw == null) return ""
        if (config.type != DbType.MYSQL && config.type != DbType.SQLSERVER) return ""
        if (!Regex("""^[A-Za-z0-9_]+$""").matches(raw)) return ""
        return " COLLATE $raw"
    }

    // Переносим только простые литералы дефолта (число/строка/NULL/CURRENT_TIMESTAMP) — сложные
    // SQL-выражения источника специфичны для его диалекта, транслятор выражений не пишем
    // (см. Шаг 10 инструкции), такие дефолты молча пропускаются.
    private fun safeDefaultSql(raw: String?): String? {
        if (raw == null) return null
        val trimmed = raw.trim()
        return when {
            trimmed.equals("NULL", ignoreCase = true) -> "NULL"
            trimmed.uppercase().startsWith("CURRENT_TIMESTAMP") -> "CURRENT_TIMESTAMP"
            Regex("""^-?\d+(\.\d+)?$""").matches(trimmed) -> trimmed
            Regex("""^'(?:[^'\\]|\\.)*'$""").matches(trimmed) -> trimmed
            else -> null
        }
    }

    override fun syncAutoIncrement(table: String, column: String, maxValue: Long) {
        val sql = when (config.type) {
            DbType.MYSQL -> "ALTER TABLE ${quote(table)} AUTO_INCREMENT = ${maxValue + 1}"
            DbType.POSTGRESQL ->
                "SELECT setval(pg_get_serial_sequence('${table}', '${column}'), $maxValue)"
            DbType.SQLITE -> {
                connection.createStatement().use { stmt ->
                    val updated = stmt.executeUpdate("UPDATE sqlite_sequence SET seq = $maxValue WHERE name = '$table'")
                    if (updated == 0) {
                        stmt.execute("INSERT INTO sqlite_sequence (name, seq) VALUES ('$table', $maxValue)")
                    }
                }
                connection.commit()
                return
            }
            DbType.SQLSERVER -> "DBCC CHECKIDENT ('${table}', RESEED, $maxValue)"
        }
        connection.createStatement().use { it.execute(sql) }
        connection.commit()
    }

    override fun createView(name: String, definition: String) {
        connection.createStatement().use { stmt ->
            // Тот же принцип, что и для таблиц (Шаг 4): существующая view безусловно
            // пересоздаётся, без попытки проверить совместимость.
            stmt.execute("DROP VIEW IF EXISTS ${quote(name)}")
            stmt.execute("CREATE VIEW ${quote(name)} AS $definition")
        }
        connection.commit()
    }

    override fun createIndexesAndConstraints(structure: TableStructure) {
        connection.createStatement().use { stmt ->
            for (idx in structure.indexes) {
                val uniqueSql = if (idx.unique) "UNIQUE " else ""
                val cols = idx.columns.joinToString(", ") { quote(it) }
                // Имя индекса префиксуется именем таблицы: в Postgres/MSSQL имена индексов должны
                // быть уникальны в рамках схемы, а не только таблицы — исходное имя источника
                // само по себе такой гарантии не даёт.
                stmt.execute("CREATE ${uniqueSql}INDEX ${quote("${structure.name}_${idx.name}")} ON ${quote(structure.name)} ($cols)")
            }
            // SQLite не поддерживает ALTER TABLE ADD CONSTRAINT CHECK — CHECK там можно задать
            // только в момент CREATE TABLE, которое createTable() (пока) не делает; пропускаем.
            if (config.type != DbType.SQLITE) {
                for (chk in structure.checkConstraints) {
                    stmt.execute(
                        "ALTER TABLE ${quote(structure.name)} ADD CONSTRAINT ${quote("${structure.name}_${chk.name}")} " +
                            "CHECK (${chk.expression})"
                    )
                }
            }
        }
        connection.commit()
    }

    override fun createForeignKeys(table: String, foreignKeys: List<ForeignKeyRef>) {
        // SQLite не поддерживает ADD CONSTRAINT FOREIGN KEY через ALTER TABLE — FK там можно
        // задать только в момент CREATE TABLE. Осознанно пропускаем без ошибки: остальные
        // СУБД получают полноценные FK-constraint'ы, для SQLite это известное ограничение.
        if (foreignKeys.isEmpty() || config.type == DbType.SQLITE) return
        connection.createStatement().use { stmt ->
            for ((idx, fk) in foreignKeys.withIndex()) {
                val constraintName = "fk_${table}_${fk.columnName}_$idx"
                val sql = "ALTER TABLE ${quote(table)} ADD CONSTRAINT ${quote(constraintName)} " +
                    "FOREIGN KEY (${quote(fk.columnName)}) REFERENCES ${quote(fk.referencedTable)} (${quote(fk.referencedColumn)}) " +
                    "ON DELETE ${actionSql(fk.onDelete)} ON UPDATE ${actionSql(fk.onUpdate)}"
                stmt.execute(sql)
            }
        }
        connection.commit()
    }

    private fun actionSql(action: ReferentialAction): String = when (action) {
        ReferentialAction.CASCADE -> "CASCADE"
        ReferentialAction.SET_NULL -> "SET NULL"
        ReferentialAction.RESTRICT -> "RESTRICT"
        ReferentialAction.SET_DEFAULT -> "SET DEFAULT"
        ReferentialAction.NO_ACTION -> "NO ACTION"
    }

    override fun insertBatch(table: String, rows: List<Map<String, Any?>>) {
        if (rows.isEmpty()) return
        val columns = rows.first().keys.toList()
        val placeholders = columns.joinToString(", ") { "?" }
        val columnsSql = columns.joinToString(", ") { quote(it) }
        val sql = "INSERT INTO ${quote(table)} ($columnsSql) VALUES ($placeholders)"

        // MSSQL по умолчанию запрещает явно вставлять значения в IDENTITY-колонку — а копирование
        // всегда переносит оригинальные PK-значения источника, поэтому для таких таблиц вставку
        // нужно обрамить SET IDENTITY_INSERT ON/OFF (в отличие от MySQL AUTO_INCREMENT/Postgres
        // GENERATED BY DEFAULT/SQLite AUTOINCREMENT, которые разрешают явные значения без этого).
        val needsIdentityInsert = config.type == DbType.SQLSERVER && hasIdentityColumn(table)
        if (needsIdentityInsert) connection.createStatement().use { it.execute("SET IDENTITY_INSERT ${quote(table)} ON") }
        try {
            connection.prepareStatement(sql).use { ps ->
                for (row in rows) {
                    columns.forEachIndexed { idx, col -> ps.setObject(idx + 1, row[col]) }
                    ps.addBatch()
                }
                ps.executeBatch()
            }
        } finally {
            if (needsIdentityInsert) connection.createStatement().use { it.execute("SET IDENTITY_INSERT ${quote(table)} OFF") }
        }
        connection.commit()
    }

    private fun hasIdentityColumn(table: String): Boolean {
        connection.createStatement().use { stmt ->
            stmt.executeQuery(
                "SELECT 1 FROM sys.identity_columns c JOIN sys.tables t ON c.object_id = t.object_id " +
                    "WHERE t.name = '${table.replace("'", "''")}'"
            ).use { rs -> return rs.next() }
        }
    }

    override fun tableExists(table: String): Boolean {
        val sql = if (config.type == DbType.SQLITE) {
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?"
        } else {
            "SELECT table_name FROM information_schema.tables WHERE table_name = ? AND ${schemaClause()}"
        }
        connection.prepareStatement(sql).use { ps ->
            ps.setString(1, table)
            ps.executeQuery().use { rs -> return rs.next() }
        }
    }

    override fun disableForeignKeyChecks() {
        when (config.type) {
            DbType.MYSQL -> connection.createStatement().use { it.execute("SET FOREIGN_KEY_CHECKS=0") }
            DbType.POSTGRESQL -> connection.createStatement().use { it.execute("SET session_replication_role = 'replica'") }
            DbType.SQLITE -> connection.createStatement().use { it.execute("PRAGMA foreign_keys = OFF") }
            // У MSSQL нет сессионного тумблера — переключается по каждой таблице отдельно.
            DbType.SQLSERVER -> forEachTable { fullName ->
                connection.createStatement().use { it.execute("ALTER TABLE $fullName NOCHECK CONSTRAINT ALL") }
            }
        }
        connection.commit()
    }

    override fun enableForeignKeyChecks() {
        when (config.type) {
            DbType.MYSQL -> connection.createStatement().use { it.execute("SET FOREIGN_KEY_CHECKS=1") }
            DbType.POSTGRESQL -> connection.createStatement().use { it.execute("SET session_replication_role = 'origin'") }
            DbType.SQLITE -> connection.createStatement().use { it.execute("PRAGMA foreign_keys = ON") }
            // CHECK CONSTRAINT ALL (без WITH CHECK) включает проверку для новых DML, не
            // перепроверяя уже вставленные строки — то же поведение, что и у остальных СУБД здесь.
            DbType.SQLSERVER -> forEachTable { fullName ->
                connection.createStatement().use { it.execute("ALTER TABLE $fullName CHECK CONSTRAINT ALL") }
            }
        }
        connection.commit()
    }

    private fun forEachTable(action: (String) -> Unit) {
        val names = mutableListOf<String>()
        connection.createStatement().use { stmt ->
            stmt.executeQuery(
                "SELECT s.name AS schema_name, t.name AS table_name " +
                    "FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id"
            ).use { rs ->
                while (rs.next()) names.add("[${rs.getString("schema_name")}].[${rs.getString("table_name")}]")
            }
        }
        names.forEach(action)
    }

    private fun schemaClause(): String = when (config.type) {
        DbType.MYSQL -> "table_schema = '${config.database}'"
        DbType.POSTGRESQL -> "table_schema = 'public'"
        DbType.SQLSERVER -> "table_schema = 'dbo'"
        else -> "1=1"
    }

    private fun quote(identifier: String): String = when (config.type) {
        DbType.MYSQL -> "`$identifier`"
        DbType.POSTGRESQL, DbType.SQLITE -> "\"$identifier\""
        DbType.SQLSERVER -> "[$identifier]"
    }

    override fun close() {
        if (::connection.isInitialized) connection.close()
    }
}
